services:
  backend:
    # For architecture change (not available for Podman)
    # platform: linux/arm64/v8
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
  frontend:
    # For architecture change (not available for Podman)
    # platform: linux/arm64/v8
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    # Avoid dev rebuilds
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
